#include "Algorithm/Mosaic/AdaptiveColorBalancePatch.h"
#include "Algorithm/Mosaic/AdaptivePatch.h"
#include "Algorithm/Mosaic/AdaptiveIsophotePatch.h"
#include "Algorithm/Mosaic/DynamicPatch.h"
#include "Algorithm/Mosaic/ShowOverLap.h"
#include "Algorithm/Mosaic/Simple.h"
