#include "Algorithm/Mosaic/AdaptiveColorBalancePatch.h"
#include "Algorithm/Mosaic/AdaptivePatch.h"
#include "Algorithm/Mosaic/AdaptiveIsophotePatch.h"
#include "Algorithm/Mosaic/PixelWiseStrategyMosaic.h"
#include "Algorithm/Mosaic/VoronoiPartitionMosaic.h"
