#include "Algorithm/ColorBalance/MatchStatistic.h"
#include "Algorithm/Evaluation/BoundaryGradientEvaluator.h"
#include "Algorithm/ImageReconstruct/ColorBalanceReconstruct.h"
#include "Algorithm/ImageReconstruct/IsophoteConstrain.h"
#include "Algorithm/ImageReconstruct/Simple.h"
#include "Algorithm/Mosaic/DynamicPatch.h"
#include "Algorithm/Mosaic/ShowOverLap.h"
#include "Algorithm/Mosaic/Simple.h"