#include "Algorithm/CloudDetection.h"
#include "Algorithm/ColorBalance.h"
#include "Algorithm/Evaluation.h"
#include "Algorithm/Mosaic.h"
#include "Algorithm/Preprocess.h"
#include "Algorithm/Reconstruct.h"
