#pragma once
#include <Algorithm/ColorBalance/MatchStatistic.hpp>
#include <Algorithm/Evaluation/BoundaryGradientEvaluator.hpp>
#include <Algorithm/Mosaic/DynamicPatch.hpp>
#include <Algorithm/Mosaic/ShowOverLap.hpp>
#include <Algorithm/Mosaic/Simple.hpp>
#include <IO/ImageReader.hpp>
#include <IO/ImageSaveVisitor.hpp>
#include <IO/ImageShowVisitor.hpp>
