#pragma once
#include "Util/General.h"
#include <Algorithm/ColorBalance/MatchStatistic.h>
#include <Algorithm/Evaluation/BoundaryGradientEvaluator.h>
#include <Algorithm/Mosaic/DynamicPatch.h>
#include <Algorithm/Mosaic/ShowOverLap.h>
#include <Algorithm/Mosaic/Simple.h>
#include <IO/ImageReader.h>
#include <IO/ImageSaveVisitor.h>
#include <Util/ImageShow.h>
